/**
 * Katakana loanword → source-word dictionary.
 *
 * Most katakana in modern Japanese are 外来語 (gairaigo) borrowed from English.
 * Showing the source word above the katakana turns an opaque string of symbols
 * into something a learner can decode instantly ("ゲレンデ" → "Gelände").
 *
 * `src` marks the origin language when it is NOT English — that detail matters,
 * because guessing an English word for パン or アルバイト leads learners astray.
 */

export type LoanEntry = {
  /** Source word shown above the katakana. Keep it short — it sets the box width. */
  en: string
  /** Origin language when not English (de/fr/pt/nl/it/es/ru). */
  src?: string
}

/**
 * Longest-match wins during segmentation, so compound entries (アイスコーヒー)
 * are listed alongside their parts (アイス / コーヒー) and win automatically.
 */
export const KATAKANA_DICT: Record<string, LoanEntry> = {
  // ─── Convenience store / shopping ───────────────────────────────
  コンビニ: { en: "convenience (store)" },
  コンビニエンスストア: { en: "convenience store" },
  スーパー: { en: "supermarket" },
  レジ: { en: "register" },
  レシート: { en: "receipt" },
  カード: { en: "card" },
  クレジットカード: { en: "credit card" },
  ポイントカード: { en: "point card" },
  ポイント: { en: "point" },
  バーコード: { en: "barcode" },
  ビニール: { en: "vinyl" },
  エコバッグ: { en: "eco bag" },
  バッグ: { en: "bag" },
  サイズ: { en: "size" },
  セール: { en: "sale" },
  キャンペーン: { en: "campaign" },
  サービス: { en: "service" },
  スタッフ: { en: "staff" },
  アルバイト: { en: "Arbeit (part-time job)", src: "de" },
  バイト: { en: "Arbeit (part-time job)", src: "de" },
  シフト: { en: "shift" },
  オーナー: { en: "owner" },
  チェーン: { en: "chain" },

  // ─── Food & drink ───────────────────────────────────────────────
  コーヒー: { en: "coffee" },
  アイスコーヒー: { en: "iced coffee" },
  ホットコーヒー: { en: "hot coffee" },
  アイス: { en: "ice" },
  ホット: { en: "hot" },
  ミルク: { en: "milk" },
  ティー: { en: "tea" },
  ジュース: { en: "juice" },
  ビール: { en: "beer", src: "nl" },
  ワイン: { en: "wine" },
  ウイスキー: { en: "whisky" },
  ハイボール: { en: "highball" },
  カクテル: { en: "cocktail" },
  ソフトドリンク: { en: "soft drink" },
  ドリンク: { en: "drink" },
  メニュー: { en: "menu" },
  オーダー: { en: "order" },
  ラストオーダー: { en: "last order" },
  パン: { en: "pão (bread)", src: "pt" },
  サンドイッチ: { en: "sandwich" },
  サンド: { en: "sandwich" },
  ハンバーガー: { en: "hamburger" },
  ハンバーグ: { en: "Hamburg (steak)", src: "de" },
  ピザ: { en: "pizza", src: "it" },
  パスタ: { en: "pasta", src: "it" },
  スパゲッティ: { en: "spaghetti", src: "it" },
  ラーメン: { en: "lā-miàn (noodles)", src: "zh" },
  カレー: { en: "curry" },
  サラダ: { en: "salad" },
  スープ: { en: "soup" },
  デザート: { en: "dessert" },
  ケーキ: { en: "cake" },
  チョコレート: { en: "chocolate" },
  チョコ: { en: "chocolate" },
  アイスクリーム: { en: "ice cream" },
  ヨーグルト: { en: "yogurt" },
  チーズ: { en: "cheese" },
  バター: { en: "butter" },
  ソース: { en: "sauce" },
  マヨネーズ: { en: "mayonnaise", src: "fr" },
  ケチャップ: { en: "ketchup" },
  ドレッシング: { en: "dressing" },
  スナック: { en: "snack" },
  ポテト: { en: "potato" },
  フライドポテト: { en: "fried potato" },
  チキン: { en: "chicken" },
  ステーキ: { en: "steak" },
  フルーツ: { en: "fruit" },
  オレンジ: { en: "orange" },
  レモン: { en: "lemon" },
  トマト: { en: "tomato" },
  セット: { en: "set" },
  テイクアウト: { en: "takeout" },
  レストラン: { en: "restaurant" },
  カフェ: { en: "café", src: "fr" },
  バー: { en: "bar" },
  テーブル: { en: "table" },
  カウンター: { en: "counter" },
  スプーン: { en: "spoon" },
  フォーク: { en: "fork" },
  ナイフ: { en: "knife" },
  グラス: { en: "glass" },
  コップ: { en: "kop (cup)", src: "nl" },

  // ─── Train station / travel ─────────────────────────────────────
  ホーム: { en: "(plat)form" },
  プラットホーム: { en: "platform" },
  ホテル: { en: "hotel" },
  チケット: { en: "ticket" },
  タクシー: { en: "taxi" },
  バス: { en: "bus" },
  エレベーター: { en: "elevator" },
  エスカレーター: { en: "escalator" },
  トイレ: { en: "toilet" },
  ロッカー: { en: "locker" },
  コインロッカー: { en: "coin locker" },
  ラッシュ: { en: "rush" },
  ラッシュアワー: { en: "rush hour" },
  スーツケース: { en: "suitcase" },
  ツアー: { en: "tour" },
  ガイド: { en: "guide" },
  マップ: { en: "map" },
  ルート: { en: "route" },
  コース: { en: "course" },
  センター: { en: "center" },
  ビル: { en: "building" },
  デパート: { en: "department (store)" },
  アパート: { en: "apartment" },
  マンション: { en: "mansion (condo)" },
  パスポート: { en: "passport" },
  チェックイン: { en: "check-in" },
  チェックアウト: { en: "check-out" },
  フロント: { en: "front (desk)" },
  キャンセル: { en: "cancel" },
  アナウンス: { en: "announce(ment)" },
  ドア: { en: "door" },
  シート: { en: "seat" },
  ゲート: { en: "gate" },
  ターミナル: { en: "terminal" },

  // ─── Ski resort / sports ────────────────────────────────────────
  スキー: { en: "ski" },
  スノーボード: { en: "snowboard" },
  スノボ: { en: "snowboard" },
  ボード: { en: "board" },
  ゲレンデ: { en: "Gelände (slope)", src: "de" },
  リフト: { en: "lift" },
  ゴンドラ: { en: "gondola", src: "it" },
  ターン: { en: "turn" },
  カービング: { en: "carving" },
  エッジ: { en: "edge" },
  ブレーキ: { en: "brake" },
  スピード: { en: "speed" },
  バランス: { en: "balance" },
  ジャンプ: { en: "jump" },
  スタート: { en: "start" },
  ゴール: { en: "goal" },
  コーチ: { en: "coach" },
  レッスン: { en: "lesson" },
  レベル: { en: "level" },
  ビギナー: { en: "beginner" },
  スポーツ: { en: "sports" },
  トレーニング: { en: "training" },
  ウェア: { en: "wear" },
  ヘルメット: { en: "helmet" },
  ゴーグル: { en: "goggles" },
  グローブ: { en: "glove" },
  ブーツ: { en: "boots" },
  ストック: { en: "Stock (pole)", src: "de" },
  ワックス: { en: "wax" },
  パウダー: { en: "powder" },
  パウダースノー: { en: "powder snow" },
  シーズン: { en: "season" },
  ロープウェイ: { en: "ropeway" },
  ヒップ: { en: "hip" },
  フォーム: { en: "form" },
  トップ: { en: "top" },
  スタンス: { en: "stance" },
  リラックス: { en: "relax" },
  ストレッチ: { en: "stretch" },
  チーム: { en: "team" },
  ゲーム: { en: "game" },
  ルール: { en: "rule" },
  マナー: { en: "manner(s)" },
  スタイル: { en: "style" },

  // ─── Tech / everyday ────────────────────────────────────────────
  スマホ: { en: "smart phone" },
  スマートフォン: { en: "smartphone" },
  パソコン: { en: "personal computer" },
  コンピューター: { en: "computer" },
  インターネット: { en: "internet" },
  ネット: { en: "net" },
  メール: { en: "mail" },
  アプリ: { en: "app(lication)" },
  サイト: { en: "site" },
  ページ: { en: "page" },
  データ: { en: "data" },
  ファイル: { en: "file" },
  パスワード: { en: "password" },
  アカウント: { en: "account" },
  ログイン: { en: "log in" },
  クリック: { en: "click" },
  ダウンロード: { en: "download" },
  カメラ: { en: "camera" },
  テレビ: { en: "television" },
  ラジオ: { en: "radio" },
  ニュース: { en: "news" },
  ドラマ: { en: "drama" },
  アニメ: { en: "anime(ation)" },
  ゲームセンター: { en: "game center" },
  ミュージック: { en: "music" },
  イヤホン: { en: "earphone" },
  バッテリー: { en: "battery" },
  ケーブル: { en: "cable" },
  コンセント: { en: "concentric (outlet)" },
  エアコン: { en: "air conditioner" },
  テーブルタップ: { en: "table tap" },
  リモコン: { en: "remote control" },

  // ─── Work / study / social ──────────────────────────────────────
  ミーティング: { en: "meeting" },
  スケジュール: { en: "schedule" },
  プロジェクト: { en: "project" },
  プレゼン: { en: "presentation" },
  レポート: { en: "report" },
  テスト: { en: "test" },
  クラス: { en: "class" },
  グループ: { en: "group" },
  パートナー: { en: "partner" },
  メンバー: { en: "member" },
  リーダー: { en: "leader" },
  オフィス: { en: "office" },
  ビジネス: { en: "business" },
  サラリーマン: { en: "salary man" },
  インタビュー: { en: "interview" },
  アドバイス: { en: "advice" },
  チャンス: { en: "chance" },
  イメージ: { en: "image" },
  テーマ: { en: "Thema (theme)", src: "de" },
  ポイントアップ: { en: "point up" },
  パターン: { en: "pattern" },
  タイプ: { en: "type" },
  トラブル: { en: "trouble" },
  ストレス: { en: "stress" },
  プレッシャー: { en: "pressure" },
  モチベーション: { en: "motivation" },
  イベント: { en: "event" },
  パーティー: { en: "party" },
  プレゼント: { en: "present (gift)" },
  デート: { en: "date" },
  カップル: { en: "couple" },
  フリー: { en: "free" },
  オーケー: { en: "OK" },
  ノート: { en: "note(book)" },
  ペン: { en: "pen" },
  ボールペン: { en: "ball(point) pen" },
  コピー: { en: "copy" },
  プリント: { en: "print" },

  // ─── Clothing / body / home ─────────────────────────────────────
  シャツ: { en: "shirt" },
  ジャケット: { en: "jacket" },
  コート: { en: "coat" },
  セーター: { en: "sweater" },
  ズボン: { en: "jupon (trousers)", src: "fr" },
  パンツ: { en: "pants" },
  スカート: { en: "skirt" },
  ドレス: { en: "dress" },
  スーツ: { en: "suit" },
  ネクタイ: { en: "necktie" },
  ソックス: { en: "socks" },
  シューズ: { en: "shoes" },
  スリッパ: { en: "slipper" },
  ベルト: { en: "belt" },
  ポケット: { en: "pocket" },
  ベッド: { en: "bed" },
  ソファ: { en: "sofa" },
  カーテン: { en: "curtain" },
  シャワー: { en: "shower" },
  タオル: { en: "towel" },
  キッチン: { en: "kitchen" },
  リビング: { en: "living (room)" },
  トイレットペーパー: { en: "toilet paper" },

  // ─── Function words & modifiers ─────────────────────────────────
  グッド: { en: "good" },
  ベスト: { en: "best" },
  ナイス: { en: "nice" },
  シンプル: { en: "simple" },
  ソフト: { en: "soft" },
  ハード: { en: "hard" },
  ライト: { en: "light" },
  ダーク: { en: "dark" },
  ミニ: { en: "mini" },
  マックス: { en: "max" },
  プラス: { en: "plus" },
  マイナス: { en: "minus" },
  オリジナル: { en: "original" },
  スペシャル: { en: "special" },
  ラッキー: { en: "lucky" },
  ハッピー: { en: "happy" },
  クール: { en: "cool" },
  スロー: { en: "slow" },
  スムーズ: { en: "smooth" },
  クリア: { en: "clear" },
  チェック: { en: "check" },
  コントロール: { en: "control" },
  リスト: { en: "list" },
  レベルアップ: { en: "level up" },
}

/**
 * Katakana strings that are NOT loanwords: onomatopoeia, native words written in
 * katakana for emphasis, and script names. Glossing these with English would be
 * actively wrong, so they short-circuit both the dictionary and the LLM lookup.
 */
export const NON_LOANWORDS = new Set([
  // Script / language names
  "カタカナ", "ヒラガナ", "ローマジ", "ニホン", "ニホンゴ", "ニッポン",
  // Onomatopoeia & mimetic words
  "ドキドキ", "ワクワク", "ペコペコ", "ニコニコ", "キラキラ", "ゴロゴロ",
  "バタバタ", "ハラハラ", "イライラ", "ソワソワ", "フワフワ", "サラサラ",
  "ベタベタ", "ザラザラ", "ツルツル", "モチモチ", "サクサク", "パリパリ",
  "ジュージュー", "グツグツ", "ゴクゴク", "パクパク", "モグモグ",
  "スースー", "ヒヤヒヤ", "ドンドン", "バンバン", "ガンガン", "シーン",
  // Native words commonly written in katakana
  "コツ", "ウソ", "ダメ", "スゴイ", "ヤバイ", "オレ", "ボク", "アナタ",
  "コブ", "ヒザ", "コシ", "アシ", "テ", "メ", "クチ", "アタマ", "カラダ",
  "マンガ", "スミマセン", "アリガトウ", "コンニチハ", "ゴミ", "サカナ",
  "ヤマ", "ユキ", "ミズ", "クルマ", "イヌ", "ネコ", "トリ", "ハナ",
])

/** Terms whose dictionary value is an empty string are structural guards, not glosses. */
export function lookupLoanword(term: string): LoanEntry | null {
  if (NON_LOANWORDS.has(term)) return null
  const entry = KATAKANA_DICT[term]
  if (!entry || !entry.en) return null
  return entry
}

/** Longest dictionary key, used to bound the greedy match window. */
export const MAX_TERM_LENGTH = Object.keys(KATAKANA_DICT).reduce(
  (max, k) => Math.max(max, k.length),
  0
)
